# Ansible variables for K3s
# Generated automatically by Terraform via group_vars.yml.tpl
instance_name: "k3s-migration-dev"
instance_type: "GP1-XS"
# public_ip: generated dynamically by Terraform
environment: "dev"

# Tool versions
k3s_version: "v1.28.5+k3s1"
kubectl_version: "v1.28.5"
helm_version: "v3.13.3"

# K3s configuration
k3s_server_location: "/var/lib/rancher/k3s"
k3s_config_file: "/etc/rancher/k3s/k3s.yaml"
k3s_token_file: "/var/lib/rancher/k3s/server/node-token"

# Cluster configuration
k3s_server_args:
- "--write-kubeconfig-mode=644"
- "--disable=traefik"
- "--disable=servicelb"
- "--disable-cloud-controller"
- "--kubelet-arg=eviction-hard=imagefs.available<1%,nodefs.available<1%"
- "--kubelet-arg=eviction-minimum-reclaim=imagefs.available=1%,nodefs.available=1%"

# Helm configuration
helm_repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: external-dns
  url: https://kubernetes-sigs.github.io/external-dns/
- name: external-secrets
  url: https://charts.external-secrets.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami

# Scaleway credentials for External DNS (overridden via .envrc/direnv)
# scaleway_access_key: "{{ lookup('env', 'SCW_ACCESS_KEY') }}"
# scaleway_secret_key: "{{ lookup('env', 'SCW_SECRET_KEY') }}"
# scaleway_organization_id: "{{ lookup('env', 'SCW_ORGANIZATION_ID') }}"
# scaleway_project_id: "{{ lookup('env', 'SCW_PROJECT_ID') }}"
